apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: kube-prometheus-stack
stringData: |
  {{- $json := .Values.additionalScrapeConfig | fromJson }}
  prometheus-additional:
  - job_name: {{ $json.jobName }}
    metrics_path: "/federate"
    params:
      "match[]":
        {{- range $json.matchers }}
        - {{ . | quote }}
        {{- end }}
    static_configs:
      - targets:
        {{- range $json.targets }}
        - {{ . | quote }}
        {{- end }}
