apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: kube-prometheus-stack
stringData: |
  prometheus-additional: |
  - job_name: {{ .Values.additionalScrapeConfig.jobName }}
    metrics_path: "/federate"
    params:
      "match[]":
        {{- range .Values.additionalScrapeConfig.matchers }}
        - {{ . | quote }}
        {{- end }}
    static_configs:
      - targets:
        {{- range .Values.additionalScrapeConfig.targets }}
        - {{ . | quote }}
        {{- end }}
