# prometheus:
#   additionalScrapeConfig:
#     jobName: "prometheus"
#     matchers:
#       - '{job="apiserver"}'
#     targets: []

additionalScrapeConfig: "{\"jobName\":\"prometheus\",\"matchers\":[\"{job=\\\"apiserver\\\"}\"],\"targets\":[\"ch2.techmuc-valiton.com\"]}"
